### ISSUE TITLE
Copyright violation

### ISSUE THREAD

**Issue by Poussinou** [richardchien/clear-weather-android#3]
Hi @richardchien 

I found [this app](https://play.google.com/store/apps/details?id=co.BlueViolet.clearweather) on the Google Play Store. This guy just took your source code, added some ads in it and put it on the Store, without warning this is free software...

By the way, [all his apps are open source software he copied](https://play.google.com/store/apps/developer?id=Vu+Viet+My+Team)...

As you are the owner of the source code, feel free to open a request to google [here](https://support.google.com/legal/contact/lr_dmca?product=googleplay) to remove the false app from the Store, if it's your wish ;)

Don't forget to tell Google that:

* The app is licensed under MIT license and this guy is violating it;
* He is falsely claiming he made the app;
* Provide some screenshots of your own app.

**Comment by ghost** [comment]
Yes, somehow this app found its way on my phone with no uninstall options, could use some help

Sent from ProtonMail mobile

-------- Original Message --------

**Comment by stdrc** [comment]
Thank you for informing me this, @Poussinou.

@anarchynjw Could you tell me what kind of "with no uninstall options" it is? Any screenshot?

**Comment by ghost** [comment]
Looking for it now...i knew it was strange since the apk was in chinese. But ot looks like the app(apk) has hidden itself. Which is concerning....... I'm pretty good at figuring this stuff out. I'll keep you posted.

Sent from ProtonMail mobile

-------- Original Message --------

**Comment by ghost** [comment]
The app inquestion was also showing up in the fdroid app as an update. Its missisn now. Now, I'm realy suspicious...

Sent from ProtonMail mobile

-------- Original Message --------

**Comment by stdrc** [comment]
Didn't it show up in the application list in system's settings app?

**Comment by Poussinou** [comment]
This fake dev is down now. Please let me know if you find any other new copy, so I can continue to track fake developers... Will close this issue for now, do not hesitate to reopen it ;)
